[package]
name = "hpl-self-xyz-verifier"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std.workspace = true
cosmwasm-storage.workspace = true
cosmwasm-schema.workspace = true

cw-storage-plus.workspace = true
cw2.workspace = true

schemars.workspace = true
thiserror.workspace = true

hpl-interface.workspace = true
hpl-utils.workspace = true
hpl-ownable.workspace = true

hex = "0.4"
alloy = { version = "0.12.6", default-features = false, features = ["sol-types", "dyn-abi"]}
bech32 = "0.11"
sha2 = "0.10"

[dev-dependencies]
serde.workspace = true
cw-multi-test.workspace = true
